blank_issues_enabled: false
contact_links:
  - name: Educodar Community Forum on ThoughtWorks
  - url: https://groups.google.com/a/thoughtworks.com/forum/#!forum/educodar-bh
  - about: If you work at ThoughtWorks, you can discuss about Educodar here
